Message-ID: <5075aa52-04b7-451b-a568-889015f031fd@gmail.com>
Date: Thu, 16 Nov 2023 09:09:25 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: =?UTF-8?B?Tmd1eeG7hW4gQ8O0bmcgVHXhuqVu?= <nctuan22@clc.fitus.edu.vn>
From: =?UTF-8?B?Tmd1eeG7hW4gQ8O0bmcgVHXhuqVu?= <nguyencongtuan0810@gmail.com>
Subject: Chao lan 1
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

Chao lan 2


.
