+OK 447
Message-ID: <5593f1bd-d84e-4b13-999f-138d573bceac@clc.fitus.edu.vn>
Date: Thu, 16 Nov 2023 23:31:44 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: =?UTF-8?B?Tmd1eeG7hW4gQ8O0bmcgVHXhuqVu?= <nctuan22@clc.fitus.edu.vn>
From: =?UTF-8?B?Tmd1eeG7hW4gQ8O0bmcgVHXhuqVu?= <nctuan22@clc.fitus.edu.vn>
Subject: A
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

ASSSS

.
