Message-ID: <ce6832f8-03a4-42c5-b0b1-bac9bb200497@gmail.com>
Date: Thu, 16 Nov 2023 11:04:26 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: =?UTF-8?B?Tmd1eeG7hW4gQ8O0bmcgVHXhuqVu?= <nctuan22@clc.fitus.edu.vn>
From: =?UTF-8?B?Tmd1eeG7hW4gQ8O0bmcgVHXhuqVu?= <nguyencongtuan0810@gmail.com>
Subject: Huuheuhfuehuehf
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

Hello World

