Message-ID: <87a0281f-4960-4657-ba09-be2cf8fd61b8@gmail.com>
Date: Thu, 16 Nov 2023 23:30:22 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: =?UTF-8?B?Tmd1eeG7hW4gQ8O0bmcgVHXhuqVu?= <nctuan22@clc.fitus.edu.vn>
From: =?UTF-8?B?Tmd1eeG7hW4gQ8O0bmcgVHXhuqVu?= <nguyencongtuan0810@gmail.com>
Subject: Csdasd
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

fdfdfdfdf

